version: "3.9"

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: image-kupipodariday-backend
    restart: unless-stopped
    ports:
      - "4000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - database


  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: image-kupipodariday-frontend
    restart: unless-stopped
    ports:
      - "8081:80"
    depends_on:
      - backend

  database:
    container_name: postgres
    image: postgres:15
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

